// Generated by CoffeeScript 1.9.1
var Session, app, express, generateSessionID, http, io, ref, serverIpAddress, serverPort;

express = require('express');

app = express();

http = require('http').Server(app);

io = require('socket.io')(http);

ref = require('./socket'), generateSessionID = ref.generateSessionID, Session = ref.Session;

serverPort = process.env.OPENSHIFT_NODEJS_PORT || 8000;

serverIpAddress = process.env.OPENSHIFT_NODEJS_IP || 'localhost';

app.get('/', function(req, res) {
  return res.redirect('/session/' + generateSessionID());
});

app.get('/session/:id', function(req, res) {
  return res.sendFile(__dirname + "/client/session.html");
});

app.use('/client', express["static"](__dirname + "/client"));

Session(io);

http.listen(serverPort, serverIpAddress, function() {
  return console.log('listening on *:8000', arguments);
});
