// Generated by CoffeeScript 1.9.1
var app, express, http, io, serverIpAddress, serverPort;

express = require('express');

app = express();

http = require('http').Server(app);

io = require('socket.io')(http);

serverPort = process.env.OPENSHIFT_NODEJS_PORT || 8000;

serverIpAddress = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';

app.get('/', function(req, res) {
  return res.send('<h1>Hello world</h1>');
});

app.get('/session/:id', function(req, res) {
  return res.sendFile(__dirname + "/client/session.html");
});

app.use('/client', express["static"](__dirname + "/client"));

io.on('connection', function(socket) {
  return console.log('a user connected');
});

http.listen(serverPort, serverIpAddress, function() {
  return console.log('listening on *:3000');
});
