// Generated by CoffeeScript 1.9.1
var SocketManager, app, express, http, io, serverIpAddress, serverPort;

express = require('express');

app = express();

http = require('http').Server(app);

io = require('socket.io')(http);

SocketManager = require('./socket');

serverPort = process.env.OPENSHIFT_NODEJS_PORT || 8000;

serverIpAddress = process.env.OPENSHIFT_NODEJS_IP || 'localhost';

app.get('/', function(req, res) {
  return res.send('<h1>Hello world</h1>');
});

app.get('/session/:id', function(req, res) {
  return res.sendFile(__dirname + "/client/session.html");
});

app.use('/client', express["static"](__dirname + "/client"));

SocketManager(io);

http.listen(serverPort, serverIpAddress, function() {
  return console.log('listening on *:8000', arguments);
});
