// Generated by LiveScript 1.3.1
module.exports = function(io){
  return io.on('connection', function(socket){
    console.log('a user connected');
    socket.on('join', function(data){
      console.log('want join', data);
      return socket.join(data.room);
    });
    socket.on('wantPlaylist', function(data){
      console.log('want playlist in rooms ', socket.rooms);
      return function(s){
        return s.emit('wantPlaylist', socket.id);
      }(
      function(room){
        return socket.broadcast.to(room);
      }(
      function(r){
        return r[0];
      }(
      socket.rooms.filter(function(r){
        return r !== socket.id;
      }))));
    });
    socket.on('replyPlaylist', function(arg$){
      var playlist, target;
      playlist = arg$.playlist, target = arg$.target;
      console.log('reply with playlist ', playlist, 'to', target);
      return socket.broadcast.to(target).emit('replyPlaylist', playlist);
    });
    return socket.on('updatePlaylist', function(playlist){
      console.log('someone wants to update', playlist);
      return socket.broadcast.emit('updatePlaylist', playlist);
    });
  });
};